# Generated by Django 3.0.4 on 2020-07-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
