# Generated by Django 3.0.4 on 2020-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_database', '0004_auto_20200715_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='origin',
            field=models.CharField(choices=[('STUDIO', 'studio'), ('LIVE', 'live'), ('COMPILATION', 'compilation')], max_length=15, null=True),
        ),
    ]
