# Generated by Django 3.0.4 on 2020-07-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_database', '0005_auto_20200715_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='issue',
            field=models.CharField(blank=True, choices=[('ORIGINAL', 'original'), ('REISSUE', 'reissue'), ('REMASTER', 'remaster')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='release_type',
            field=models.CharField(blank=True, choices=[('ALBUM', 'album'), ('SINGLE', 'single'), ('TRACK', 'track')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(blank=True, choices=[('RELEASED', 'released'), ('UPCOMING', 'upcoming')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='origin',
            field=models.CharField(blank=True, choices=[('STUDIO', 'studio'), ('LIVE', 'live'), ('COMPILATION', 'compilation')], max_length=15, null=True),
        ),
    ]
