# Generated by Django 3.0.4 on 2020-07-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_database', '0006_auto_20200715_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Release',
        ),
    ]
