# Generated by Django 3.0.4 on 2020-07-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_database', '0008_artist_chart_country_genre_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.AddField(
            model_name='chart',
            name='releases',
            field=models.ManyToManyField(to='music_database.Release'),
        ),
        migrations.AddField(
            model_name='genre',
            name='releases',
            field=models.ManyToManyField(to='music_database.Release'),
        ),
        migrations.AddField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(to='music_database.Artist'),
        ),
        migrations.AddField(
            model_name='release',
            name='charts',
            field=models.ManyToManyField(to='music_database.Chart'),
        ),
        migrations.AddField(
            model_name='release',
            name='genres',
            field=models.ManyToManyField(to='music_database.Genre'),
        ),
    ]
