# Generated by Django 3.0.4 on 2020-07-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_database', '0010_auto_20200716_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='releases',
            field=models.ManyToManyField(blank=True, to='music_database.Release'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='releases',
            field=models.ManyToManyField(blank=True, to='music_database.Release'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='releases',
            field=models.ManyToManyField(blank=True, to='music_database.Release'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(blank=True, to='music_database.Artist'),
        ),
        migrations.AlterField(
            model_name='release',
            name='charts',
            field=models.ManyToManyField(blank=True, to='music_database.Chart'),
        ),
        migrations.AlterField(
            model_name='release',
            name='genres',
            field=models.ManyToManyField(blank=True, to='music_database.Genre'),
        ),
    ]
