# Generated by Django 3.0.4 on 2020-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_database', '0011_auto_20200716_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
